print("bollen data type false-condition")
print(10>9)
print(10==10)
print(10<9)
print("false statement")
print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))
print("true statement")
print(bool(True))
